# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImageNet1K

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ImageRecord(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ImageRecord()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImageRecord(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ImageRecordBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x49\x4E\x31\x4B", size_prefixed=size_prefixed)

    # ImageRecord
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImageRecord
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ImageRecord
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ImageRecord
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ImageRecord
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ImageRecord
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ImageRecord
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # ImageRecord
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # ImageRecord
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # ImageRecord
    def Channels(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 3

    # ImageRecord
    def Encoding(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def ImageRecordStart(builder):
    builder.StartObject(7)

def Start(builder):
    ImageRecordStart(builder)

def ImageRecordAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    ImageRecordAddData(builder, data)

def ImageRecordStartDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartDataVector(builder, numElems):
    return ImageRecordStartDataVector(builder, numElems)

def ImageRecordAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    ImageRecordAddId(builder, id)

def ImageRecordAddLabel(builder, label):
    builder.PrependInt16Slot(2, label, 0)

def AddLabel(builder, label):
    ImageRecordAddLabel(builder, label)

def ImageRecordAddWidth(builder, width):
    builder.PrependUint16Slot(3, width, 0)

def AddWidth(builder, width):
    ImageRecordAddWidth(builder, width)

def ImageRecordAddHeight(builder, height):
    builder.PrependUint16Slot(4, height, 0)

def AddHeight(builder, height):
    ImageRecordAddHeight(builder, height)

def ImageRecordAddChannels(builder, channels):
    builder.PrependUint8Slot(5, channels, 3)

def AddChannels(builder, channels):
    ImageRecordAddChannels(builder, channels)

def ImageRecordAddEncoding(builder, encoding):
    builder.PrependUint8Slot(6, encoding, 0)

def AddEncoding(builder, encoding):
    ImageRecordAddEncoding(builder, encoding)

def ImageRecordEnd(builder):
    return builder.EndObject()

def End(builder):
    return ImageRecordEnd(builder)
